# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/workspace

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/workspace/src

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/src/CMakeFiles /home/ubuntu/workspace/src/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/workspace/src/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named project

# Build rule for target.
project: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 project
.PHONY : project

# fast build rule for target.
project/fast:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/build
.PHONY : project/fast

Block.o: Block.cpp.o
.PHONY : Block.o

# target to build an object file
Block.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Block.cpp.o
.PHONY : Block.cpp.o

Block.i: Block.cpp.i
.PHONY : Block.i

# target to preprocess a source file
Block.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Block.cpp.i
.PHONY : Block.cpp.i

Block.s: Block.cpp.s
.PHONY : Block.s

# target to generate assembly for a file
Block.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Block.cpp.s
.PHONY : Block.cpp.s

LinkedList.o: LinkedList.cpp.o
.PHONY : LinkedList.o

# target to build an object file
LinkedList.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedList.cpp.o
.PHONY : LinkedList.cpp.o

LinkedList.i: LinkedList.cpp.i
.PHONY : LinkedList.i

# target to preprocess a source file
LinkedList.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedList.cpp.i
.PHONY : LinkedList.cpp.i

LinkedList.s: LinkedList.cpp.s
.PHONY : LinkedList.s

# target to generate assembly for a file
LinkedList.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/LinkedList.cpp.s
.PHONY : LinkedList.cpp.s

Main.o: Main.cpp.o
.PHONY : Main.o

# target to build an object file
Main.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Main.cpp.o
.PHONY : Main.cpp.o

Main.i: Main.cpp.i
.PHONY : Main.i

# target to preprocess a source file
Main.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Main.cpp.i
.PHONY : Main.cpp.i

Main.s: Main.cpp.s
.PHONY : Main.s

# target to generate assembly for a file
Main.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Main.cpp.s
.PHONY : Main.cpp.s

MemPool.o: MemPool.cpp.o
.PHONY : MemPool.o

# target to build an object file
MemPool.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemPool.cpp.o
.PHONY : MemPool.cpp.o

MemPool.i: MemPool.cpp.i
.PHONY : MemPool.i

# target to preprocess a source file
MemPool.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemPool.cpp.i
.PHONY : MemPool.cpp.i

MemPool.s: MemPool.cpp.s
.PHONY : MemPool.s

# target to generate assembly for a file
MemPool.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemPool.cpp.s
.PHONY : MemPool.cpp.s

MemoryManager.o: MemoryManager.cpp.o
.PHONY : MemoryManager.o

# target to build an object file
MemoryManager.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemoryManager.cpp.o
.PHONY : MemoryManager.cpp.o

MemoryManager.i: MemoryManager.cpp.i
.PHONY : MemoryManager.i

# target to preprocess a source file
MemoryManager.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemoryManager.cpp.i
.PHONY : MemoryManager.cpp.i

MemoryManager.s: MemoryManager.cpp.s
.PHONY : MemoryManager.s

# target to generate assembly for a file
MemoryManager.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/MemoryManager.cpp.s
.PHONY : MemoryManager.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Object.cpp.s
.PHONY : Object.cpp.s

Operators.o: Operators.cpp.o
.PHONY : Operators.o

# target to build an object file
Operators.cpp.o:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Operators.cpp.o
.PHONY : Operators.cpp.o

Operators.i: Operators.cpp.i
.PHONY : Operators.i

# target to preprocess a source file
Operators.cpp.i:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Operators.cpp.i
.PHONY : Operators.cpp.i

Operators.s: Operators.cpp.s
.PHONY : Operators.s

# target to generate assembly for a file
Operators.cpp.s:
	$(MAKE) -f CMakeFiles/project.dir/build.make CMakeFiles/project.dir/Operators.cpp.s
.PHONY : Operators.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... project"
	@echo "... rebuild_cache"
	@echo "... Block.o"
	@echo "... Block.i"
	@echo "... Block.s"
	@echo "... LinkedList.o"
	@echo "... LinkedList.i"
	@echo "... LinkedList.s"
	@echo "... Main.o"
	@echo "... Main.i"
	@echo "... Main.s"
	@echo "... MemPool.o"
	@echo "... MemPool.i"
	@echo "... MemPool.s"
	@echo "... MemoryManager.o"
	@echo "... MemoryManager.i"
	@echo "... MemoryManager.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... Operators.o"
	@echo "... Operators.i"
	@echo "... Operators.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

